server:
  port: 8080

spring:
  data:
    mongodb:
      authentication-database: admin
#      username:
#      password:
      database: testDB
      port: 27017
      host: localhost
      # auto index creation for @Indexed annotation
      auto-index-creation: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # Multipart file configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true